"""Generate original synthetic data and executable notebooks. Run from any directory."""
from pathlib import Path
import json, textwrap, sys
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]
specs=json.loads((ROOT/'scripts/project_specs.json').read_text())
connect='''## Author

**Tajamul Khan**

[GitHub](https://github.com/tajamulkhann) · [LinkedIn](https://www.linkedin.com/in/tajamulkhann/) · [Instagram](https://www.instagram.com/tajamul.codes/) · [Mentorship](https://topmate.io/tajamulkhan)

## Let's Connect

<div align="center">
<a href="https://www.linkedin.com/in/tajamulkhann/"><img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white"></a>
<a href="https://www.instagram.com/tajamul.codes/"><img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white"></a>
<a href="https://topmate.io/tajamulkhan"><img src="https://img.shields.io/badge/Topmate-FF0000?style=for-the-badge"></a>
<a href="https://www.whatsapp.com/channel/0029VaYs05jJkK7JKCesw42f"><img src="https://img.shields.io/badge/WhatsApp-25D366?style=for-the-badge&logo=whatsapp&logoColor=white"></a>
<a href="https://t.me/tajamul_khan"><img src="https://img.shields.io/badge/Telegram-26A5E4?style=for-the-badge&logo=telegram&logoColor=white"></a>
<a href="https://substack.com/@tajamulkhan"><img src="https://img.shields.io/badge/Substack-FF6719?style=for-the-badge&logo=substack&logoColor=white"></a>
<a href="https://www.kaggle.com/tajamulkhan"><img src="https://img.shields.io/badge/Kaggle-035a7d?style=for-the-badge&logo=kaggle&logoColor=white"></a>
<a href="https://github.com/tajamulkhann"><img src="https://img.shields.io/badge/GitHub-12100E?style=for-the-badge&logo=github&logoColor=white"></a>
<a href="https://medium.com/@tajamulkhan"><img src="https://img.shields.io/badge/Medium-12100E?style=for-the-badge&logo=medium&logoColor=white"></a>
</div>
'''
(ROOT/'scripts/connect.md').write_text(connect)
def md(s):return dict(cell_type='markdown',metadata={},source=s.splitlines(True))
def code(s):return dict(cell_type='code',metadata={},execution_count=None,outputs=[],source=s.splitlines(True))
for i,s in enumerate(specs):
 p=ROOT/'data-analytics'/s['slug'];(p/'data').mkdir(parents=True,exist_ok=True);(p/'outputs').mkdir(exist_ok=True)
 generation='''from pathlib import Path
import numpy as np
import pandas as pd
rng=np.random.default_rng(SEED)
dates=pd.date_range('2025-01-01','2025-12-31',freq='D')
'''.replace('SEED',str(202600+i))+s['generation']+"\nif __name__ == '__main__':\n    df.to_csv(Path(__file__).parent/'data'/'raw.csv',index=False)\n    print('Generated',len(df),'synthetic rows')\n"
 (p/'generate_data.py').write_text(generation)
 ns={'__name__':'generator'};exec(generation,ns);df=ns['df'];df.to_csv(p/'data/raw.csv',index=False)
 dictionary=['# Dataset dictionary','', '**Source:** Original synthetic teaching dataset generated by `generate_data.py`. No external rows or personal data are included.','',f'**Seed:** {202600+i}. **Raw rows:** {len(df):,}. Monetary fields use USD. Dates describe a fictional 2025 observation window.','',s['definitions'],'','| Column | Type | Example |','|---|---|---|']
 for col in df:
  dictionary.append(f'| `{col}` | {df[col].dtype} | `{df[col].dropna().iloc[0]}` |')
 dictionary += ['', '## Generation and interpretation', '', 'The generator is the authoritative field-level construction recipe. Relationships and rates are deliberately simulated for teaching and must not be presented as evidence about a real business. Missing values are intentional where an outcome is unobserved; the retail file contains 12 deliberate duplicate lines.', '', '## Usage', '', 'Included synthetic data is released under CC0-1.0. See the root DATA_LICENSE.md.']
 (p/'data/README.md').write_text('\n'.join(dictionary))
 (p/'analysis.sql').write_text('-- SQLite dialect. facts is created by analysis.ipynb after validation.\n'+s['sql']+'\n')
 setup="""from pathlib import Path
import json, sqlite3
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display
BASE = Path.cwd()
assert (BASE/'data/raw.csv').exists(), 'Run from this project directory'
OUT = BASE/'outputs'
OUT.mkdir(exist_ok=True)
pd.set_option('display.max_columns', 20)
plt.rcParams.update({'figure.dpi':120, 'axes.spines.top':False, 'axes.spines.right':False})
df = pd.read_csv(BASE/'data/raw.csv')
if 'date' in df:
    df['date'] = pd.to_datetime(df['date'])
print('Raw shape:',df.shape)
display(df.head())
"""
 audit="""audit=pd.DataFrame({'dtype':df.dtypes.astype(str),'missing':df.isna().sum(),'unique_values':df.nunique()})
display(audit)
print('Exact duplicate rows:',df.duplicated().sum())
audit.to_csv(OUT/'data_quality.csv')
"""
 evidence="""display(summary.round(4))
display(pd.Series(metrics,name='value').to_frame())
summary.to_csv(OUT/'summary.csv')
(OUT/'metrics.json').write_text(json.dumps({k:float(v) for k,v in metrics.items()},indent=2))
df.to_csv(OUT/'analysis_ready.csv',index=False)
assert all(np.isfinite(float(v)) for v in metrics.values()), 'Invalid KPI'
"""
 sql="""with sqlite3.connect(':memory:') as conn:
    df.to_sql('facts',conn,index=False,if_exists='replace')
    sql_result=pd.read_sql_query((BASE/'analysis.sql').read_text(),conn)
display(sql_result)
sql_result.to_csv(OUT/'sql_results.csv',index=False)
# Reconcile at least one common aggregate by group, rather than trusting the SQL output.
key=sql_result.columns[0]
py=summary.reset_index()
common=[c for c in sql_result.columns[1:] if c in py.columns]
assert common, 'No comparable aggregate'
joined=sql_result.merge(py,on=key,suffixes=('_sql','_python'),validate='one_to_one')
assert len(joined)==len(summary)==len(sql_result)
for col in common:
    assert np.allclose(joined[col+'_sql'],joined[col+'_python'],rtol=1e-8,atol=1e-6), col
print('SQL / Python reconciliation passed:',common)
"""
 # Custom SQL names must expose one exact comparable measure.
 fixes={2:('customers','customers'),4:('sessions','visit'),6:('headcount','starting_headcount'),8:('users','users')}
 if i==4: sql=sql.replace("key=sql_result.columns[0]", "sql_result=sql_result.rename(columns={'sessions':'visit'})\nkey=sql_result.columns[0]")
 if i==6: sql=sql.replace("key=sql_result.columns[0]", "sql_result=sql_result.rename(columns={'headcount':'starting_headcount'})\nkey=sql_result.columns[0]")
 plot="""fig,ax=plt.subplots(figsize=(9,4.6))
chart.plot(kind='bar',ax=ax,color='#246577',rot=25)
ax.set_ylabel(ylabel)
ax.set_xlabel('')
ax.set_title(TITLE,loc='left',fontweight='bold',pad=15)
fig.tight_layout()
fig.savefig(OUT/'overview.png',bbox_inches='tight')
plt.show()
""".replace('TITLE',repr(s['title']))
 dashboard="""# Standalone dashboard: no remote JavaScript, server or account required.
import html, base64
cards=''.join('<article><span>'+html.escape(k)+'</span><strong>'+f'{v:,.4f}'+'</strong></article>' for k,v in metrics.items())
image=base64.b64encode((OUT/'overview.png').read_bytes()).decode()
table=summary.round(4).to_html(classes='data',border=0)
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>PROJECT_TITLE</title>
<style>body{font:16px system-ui;margin:0;background:#f3f5f7;color:#172c3b}main{max-width:1100px;margin:auto;padding:36px}header{border-bottom:3px solid #246577;margin-bottom:24px}small{color:#51616c}.cards{display:flex;gap:14px;flex-wrap:wrap}article{background:white;padding:18px;border:1px solid #d7e0e5;flex:1;min-width:175px}strong{display:block;font-size:27px;margin-top:12px}img{max-width:100%;margin-top:24px}table{border-collapse:collapse;background:white;width:100%;font-size:14px}td,th{padding:12px;text-align:right;border-bottom:1px solid #d7e0e5}input{padding:12px;margin:20px 0;width:280px;max-width:90%}.scroll{overflow:auto}footer{margin-top:24px}</style>
<main><header><small>TAJAMUL KHAN · DATA ANALYST PORTFOLIO</small><h1>PROJECT_TITLE</h1><p>PROJECT_QUESTION</p><p><b>Synthetic teaching data · Fictional 2025 case study</b></p></header><section class="cards">'''+cards+'''</section><img alt="Analysis overview chart" src="data:image/png;base64,'''+image+'''"><h2>Explore summary groups</h2><label for="filter">Filter summary rows</label><br><input id="filter" placeholder="Type a group name"><div class="scroll">'''+table+'''</div><p>PROJECT_LIMIT</p><footer>Instagram @tajamul.codes · linkedin.com/in/tajamulkhann/</footer></main>
<script>document.getElementById('filter').addEventListener('input',function(){const q=this.value.toLowerCase();document.querySelectorAll('tbody tr').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(q))});</script></html>'''
detail_image=base64.b64encode((OUT/'detail.png').read_bytes()).decode()
page=page.replace('<h2>Explore summary groups</h2>','<h2>Analyst finding</h2><p>'+html.escape(recommendation)+'</p><img alt="Supporting analysis" src="data:image/png;base64,'+detail_image+'"><h2>Explore summary groups</h2>')
(OUT/'dashboard.html').write_text(page)
print('Saved dashboard.html, overview.png, summary.csv, metrics.json, SQL results and analysis-ready data.')
""".replace('PROJECT_TITLE',s['title']).replace('PROJECT_QUESTION',s['question']).replace('PROJECT_LIMIT',s['limit'])
 cells=[md(f"# {s['title']}\n\n**Author: Tajamul Khan**\n\n{s['question']}\n\nOriginal synthetic teaching data. All outputs below are calculated by executing these cells. This is an analytical portfolio case study, not a real client engagement."),md('## Situation and task\n\n'+s['situation']+'\n\n'+s['task']),md('## Data contract and KPI definitions\n\n'+s['definitions']+'\n\nSee `data/README.md` for field types, source and seed.'),code(setup),md('## Validate the source\n\nInspect missingness and grain before computing metrics. Missing outcomes are not automatically zeros.'),code(audit),md('## Action: analysis\n\n'+s['action']),code(s['analysis']),md('## Results: calculated evidence\n\nThese describe only the included synthetic dataset. They do not measure deployed impact.'),code(evidence),md('## SQL cross-check\n\nLoad validated facts into SQLite and reconcile shared aggregates against Python.'),code(sql),md('## Visual interpretation'),code(plot),md('## Offline dashboard\n\nThe KPI cards and chart are a fixed analysis snapshot. The row filter searches the summary table; it does not recompute the KPIs.'),code(dashboard),md('## Decision, limitations and next step\n\n'+s['limit']+'\n\n**Next step:** '+s['extension']+'\n\nUse the result table to identify a priority for investigation. Avoid claiming that the suggested action has already delivered a business improvement.\n\n## Career discussion\n\nExplain the business question, data grain, denominator, validation, strongest finding and one limitation. Use the README STAR story only after reproducing and understanding this project.')]
 deep_title,deep_explanation,deep_code=json.loads((ROOT/'scripts/deep_dive_specs.json').read_text())[i]
 deep_code += "\ndetail.to_csv(OUT/'detail.csv')\nprint(recommendation)\n(OUT/'recommendation.txt').write_text(recommendation+'\\n')\n"
 cells[8:8]=[md('## Deep dive: '+deep_title+'\n\n'+deep_explanation),code(deep_code)]
 nb={'cells':cells,'metadata':{'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python','version':sys.version.split()[0]}},'nbformat':4,'nbformat_minor':5}
 import uuid
 for c in cells:c['id']=uuid.uuid4().hex[:8]
 (p/'analysis.ipynb').write_text(json.dumps(nb,indent=1))
 (p/'analysis.py').write_text('# Run from this project directory. Notebook companion with identical code.\n\n'+'\n\n'.join(''.join(c['source']) for c in cells if c['cell_type']=='code'))
print('Built ten datasets and notebooks')
